spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: root
          password: root
          # url: jdbc:mysql://127.0.0.1:3306/spring-boot-demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
          url: jdbc:mysql://118.89.222.159:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
          driver-class-name: com.mysql.cj.jdbc.Driver
        slave:
          url: jdbc:sqlserver://118.89.222.159:1433;DatabaseName=test
          username: sa
          password: Guan543543
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      mp-enabled: true
  logging:
     file: yanfa.log
     path: c:/mylogs
     level:
       #com.xkcoding.multi.datasource.mybatis: info,debug
       com.xkcoding.multi.datasource.mybatis: info
   